### ISSUE TITLE
Adding time retrospectively

### ISSUE THREAD

**Issue by epicalex** [Neverbland/slack-harvest#2]
### Aim
At the end of the day, to add any missed time you still need to open Harvest. This removes that need.

###Requirements
For example 

`/t update NEVERBLAND Internal 2:30`
Or the normal conversation flow

**Comment by gacek85** [comment]
This will be rather done using the dialog flow (like with the start action), cuz otherwise it will be absolutely not user friendly

**Comment by gacek85** [comment]
That is in the 0.3 release, tested, merged to develop/master, closing.
